env:
  commonjs: true
  es2020: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules: 
  no-extra-semi: "error"
  semi: ["error", "always"]
  comma-dangle: ["error", "only-multiline"]
